// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env.NEON_STORAGE_DATABASE_URL_UNPOOLED
      ?? process.env.NEON_STORAGE_DATABASE_URL
      ?? process.env.DATABASE_URL,
  },
});
